DoAn/Models/DanhMuc.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMuc()
        {
            this.LoaiBais = new HashSet<LoaiBai>();
        }
    
        public int DanhMucId { get; set; }
        public string TenDanhMuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoaiBai> LoaiBais { get; set; }
    }
}

DoAn/Models/TracNghiem.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

DoAn/Areas/Admin/Controllers/DanhMucController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAn.Models;

namespace DoAn.Areas.Admin.Controllers
{
    public class DanhMucController : Controller
    {
        private TracNghiem1Entities db = new TracNghiem1Entities();

        // GET: Admin/DanhMuc
        public ActionResult Index()
        {
            return View(db.DanhMucs.ToList());
        }

        // GET: Admin/DanhMuc/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // GET: Admin/DanhMuc/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/DanhMuc/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DanhMucId,TenDanhMuc")] DanhMuc danhMuc)
        {
            if (ModelState.IsValid)
            {
                db.DanhMucs.Add(danhMuc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(danhMuc);
        }

        // GET: Admin/DanhMuc/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // POST: Admin/DanhMuc/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DanhMucId,TenDanhMuc")] DanhMuc danhMuc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(danhMuc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(danhMuc);
        }

        // GET: Admin/DanhMuc/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // POST: Admin/DanhMuc/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            db.DanhMucs.Remove(danhMuc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAn/Controllers/TracNghiemController.cs
using DoAn.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static DoAn.ModelsView.ViewModels;

namespace DoAn.Controllers
{
    public class TracNghiemController : Controller
    {
        // GET: TracNghiem

        public TracNghiem1Entities dbContext = new TracNghiem1Entities();

        public ActionResult DanhSachBai(int id)
        {
            var bai = from s in dbContext.Bais where s.LoaiBaiId == id select s;
            return View(bai);

        }

        public ActionResult DanhMuc(int id)
        {
            var danhmuc = from s in dbContext.LoaiBais where s.DanhMucId == id select s;
            return View(danhmuc);
        }

        [HttpGet]
        public ActionResult ChonBai(int id)
        {
            BaiVM quiz = new DoAn.ModelsView.ViewModels.BaiVM();
            quiz.ListOfBai = dbContext.Bais.Where(q => q.BaiId == id).Select(q => new SelectListItem
            {
                Text = q.TenBai,
                Value = id.ToString()

            }).ToList();

            return View(quiz);
        }

        [HttpPost]
        public ActionResult ChonBai(BaiVM bai)
        {
            BaiVM chonbai = dbContext.Bais.Where(q => q.BaiId == bai.BaiId).Select(q => new BaiVM
            {
                BaiId = q.BaiId,
                TenBai = q.TenBai,


            }).FirstOrDefault();

            if (chonbai != null)
            {
                Session["ChonBai"] = chonbai;

                return RedirectToAction("LamBai");
            }

            return View();
        }

        [HttpGet]
        public ActionResult LamBai()
        {
            BaiVM quizSelected = Session["ChonBai"] as BaiVM;
            IQueryable<CauHoiVM> questions = null;

            if (quizSelected != null)
            {
                questions = dbContext.CauHois.Where(q => q.Bai.BaiId == quizSelected.BaiId)
                   .Select(q => new CauHoiVM
                   {
                       CauHoiId = q.CauHoiId,
                       CauHoi = q.CauHoi1,
                       DapAn = q.DapAns.Select(c => new DapAnVM
                       {
                           DapAnId = c.DapAnId,
                           DapAn = c.DapAn1
                       }).ToList()

                   }).AsQueryable();


            }

            return View(questions);
        }

        [HttpPost]
        public ActionResult LamBai(List<KetQuaVM> ketquacautracnghiem)
        {
            List<KetQuaVM> ketquacuoicung = new List<DoAn.ModelsView.ViewModels.KetQuaVM>();

            foreach (KetQuaVM cautraloi in ketquacautracnghiem)
            {
                KetQuaVM ketqua = dbContext.KetQuas.Where(a => a.CauHoiId == cautraloi.CauHoiId).Select(a => new KetQuaVM
                {
                    CauHoiId = a.CauHoiId.Value,
                    DapAnQ = a.KetQua1,
                    isCorrect = (cautraloi.DapAnQ.ToLower().Equals(a.KetQua1.ToLower()))

                }).FirstOrDefault();

                ketquacuoicung.Add(ketqua);
            }

            return Json(new { ketqua = ketquacuoicung }, JsonRequestBehavior.AllowGet);
        }

    }

}

DoAn/Views/TracNghiem/ChonBai.cshtml
@model DoAn.ModelsView.ViewModels.BaiVM
@{
    ViewBag.Title = "BaiTheoPack";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Style.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />

<style>
    .sidebar-right .card-group-item {
        border: 1px solid #d9d9d9;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        border-radius: 5px;
        -khtml-border-radius: 5px;
        margin-bottom: 25px;
    }

    .sidebar-right .card-header:first-child {
        height: auto;
        min-height: 43px;
        background: #3a4bcd;
        padding: 10px 0 7px;
    }

    .card-header:first-child {
        border-radius: calc(0.25rem - 1px) calc(0.25rem - 1px) 0 0;
    }

    .card-header {
        padding: 0.75rem 1.25rem;
        margin-bottom: 0;
        background-color: rgba(0,0,0,.03);
        border-bottom: 1px solid rgba(0,0,0,.125);
    }

    .exam-top-list.hasScrollingBar {
        height: auto;
    }

    .sidebar-right .hasScrollingBar {
        height: 310px;
        margin-right: 10px;
    }

    .hasScrollingBar {
        position: relative;
        height: 100vh;
        overflow-x: hidden;
        scroll-behavior: smooth;
    }

    .exam-top-list .top-header, .exam-top-list .row-content {
        display: flex;
    }
    .exam-top-list .top-header {
        padding: 22px 5px 19px 3px;
    }

    .exam-top-list .exam-item {
        margin-left: 18px;
        margin-right: 8px;
        padding-bottom: 11px;
    }

    .exam-top-list .top-header, .exam-top-list .row-content {
        display: flex;
    }

        .exam-top-list .row-content .col.name {
            text-align: left;
            font-family: "Nunito", sans-serif;
            font-size: 12px;
            line-height: 1.33;
            font-weight: 700;
            padding-left: 0;
        }

        .exam-top-list .top-header .col.name, .exam-top-list .row-content .col.name {
            text-align: left;
            flex-basis: 35%;
        }

        .exam-top-list .row-content .col {
            font-family: "Nunito", sans-serif;
            font-size: 11px;
            line-height: 1.36;
            font-weight: 400;
            text-align: center;
        }

        .exam-top-list .top-header .col, .exam-top-list .row-content .col {
            flex: 1;
            font-family: "Nunito", sans-serif;
            font-size: 11px;
            line-height: 1.36;
            font-weight: 700;
            color: #0c0c0c;
            text-align: center;
        }

        .exam-top-list .row-content .col {
            font-family: "Nunito", sans-serif;
            font-size: 11px;
            line-height: 1.36;
            font-weight: 400;
            text-align: center;
        }

        .exam-top-list .row-content .col {
            font-family: "Nunito", sans-serif;
            font-size: 11px;
            line-height: 1.36;
            font-weight: 400;
            text-align: center;
        }

    .btn.gray {
        font-family: "Nunito", sans-serif;
        font-size: 13px;
        line-height: 31px;
        font-weight: 700;
        color: #535353;
        background: #f1f1f1;
        padding: 0px 26px 0px 26px;
        min-width: inherit;
        height: auto;
    }

    .exam-top-list .btn {
        margin: 4px auto 20px;
        display: table;
    }

    .sidebar-right .try-it-now {
        text-align: center;
        padding: 20px 0 30px;
    }

    .sidebar-right .try-it-now {
        text-align: center;
        padding: 20px 0 30px;
    }

    .red {
        color: #fe4500;
    }

    .sidebar-right .try-it-now .btn {
        width: 100%;
        margin-top: 12px;
        height: 54px;
        line-height: 54px;
        font-size: 13px;
    }

    .btn:not(:disabled):not(.disabled) {
        cursor: pointer;
    }

    .btn.orange {
        background: #ffb83c;
    }


    element.style {
    }

    .sidebar-right .try-it-now .btn {
        width: 100%;
        margin-top: 12px;
        height: 54px;
        line-height: 54px;
        font-size: 13px;
    }

    .btn.facebook-btn {
        background-color: #375aab;
    }

    .exam-top-list .exam-item:after {
        content: "";
        border-bottom: 1px dotted #d9d9d9;
        width: 98%;
        height: 1px;
        display: block;
        margin-top: 14px;
        margin-bottom: 6px;
    }

    .sidebar-right .card-header h2 {
        text-align: center;
        font-family: "Nunito", sans-serif;
        font-size: 20px;
        line-height: 27px;
        font-weight: 700;
        color: #fff;
    }

    .exam-top-list .row-content .col.name {
        text-align: left;
        font-family: "Nunito", sans-serif;
        font-size: 12px;
        line-height: 1.33;
        font-weight: 700;
        padding-left: 0;
    }

    .sidebar-right .try-it-now .btn {
        width: 100%;
        margin-top: 12px;
        height: 54px;
        line-height: 54px;
        font-size: 13px;
    }

</style>



<div class="breadcrumb">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="https://tracnghiem.net/">Trang chủ</a></li>
                <li class="breadcrumb-item"><a href="https://tracnghiem.net/thptqg/">Thi THPTQG </a></li>
            </ol>
        </nav>
    </div>
</div>


<div class="content-two-columns" style="height: auto !important;">
    <div class="container" style="height: auto !important;">
        <div class="SelQuiz">

            <div class="panel panel-default" style="width: 50%; margin: 10% 25%; text-align: center;">
                <div class="panel-heading"><p class="red">Bạn có muốn chinh phục đề thi này</p></div>
                <div class="panel-body">
                    @using (Html.BeginForm("ChonBai", "TracNghiem", FormMethod.Post))
                    {
                        @Html.DropDownListFor(model => model.BaiId, Model.ListOfBai, new { @class = "form-control", @style = "text-align: center" })<br />
                        <button type="submit" id="Enter" class="btn btn-success btn-lg" style="width:100%;"><span class="glyphicon glyphicon-ok"></span> Có tôi muốn</button>}
                </div>
            </div>

            <nav id="sidebar" class="sidebar-right" style="height: auto !important;">
                <input type="hidden" name="schoolTestID" value="5691">
                <article class="card-group-item" id="top-ranking">
                    <header class="card-header">
                        <h2 class="title">Top 10</h2>
                    </header>
                    <div class="exam-top-list hasScrollingBar">
                        <div class="top-header">
                            <div class="col name" style="margin-left:15px">Tên</div>
                            <div class="col">Điểm</div>
                            <div class="col">Thời gian</div>
                        </div>
                        <!-- list-group .// -->
                        <div class="exam-item">
                            <div class="row-content">
                                <div class="col name top1"><span>🥇Thinh</span></div>
                                <div class="col">10đ</div>
                                <div class="col">2:26</div>
                            </div>
                        </div> <div class="exam-item">
                            <div class="row-content">
                                <div class="col name top2"><span>🥈Thinh</span></div>
                                <div class="col">9đ</div>
                                <div class="col">61:25</div>
                            </div>
                        </div> <div class="exam-item">
                            <div class="row-content">
                                <div class="col name top3"><span>🥉Thinh</span></div>
                                <div class="col">8đ</div>
                                <div class="col">62:47</div>
                            </div>
                        </div><a href="javascript:void(0)" class="btn gray" id="load-more">Xem thêm</a>
                    </div>
                </article> <div class="try-it-now p-0">

                </div>
                <div class="try-it-now">
                    <a href="https://www.facebook.com/sharer.php?u=https://tracnghiem.net/thptqg/de-thi-thpt-qg-nam-2022-mon-toan-bo-gd-dt-ma-de-105-5691.html" class="btn facebook-btn social-btn">Chia sẻ Facebook</a>
                </div>
            </nav>



        </div>
    </div>
</div>

DoAn/Views/TracNghiem/DanhMuc.cshtml
@model IEnumerable<DoAn.Models.LoaiBai>
@{
    ViewBag.Title = "DanhMuc";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Style.css" rel="stylesheet" />

<div class="breadcrumb">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="https://tracnghiem.net/">Trang chủ</a></li>
                <li class="breadcrumb-item"><a href="https://tracnghiem.net/thptqg/">Thi THPTQG </a></li>
            </ol>
        </nav>
    </div>
</div>


<div class="content-two-columns" style="height: auto !important;">
    <div class="container" style="height: auto !important;">
        <div class="row" style="height: auto !important;">
            <!--LEFT CONTENT-->
            <div class="cot-trai">
                <!--ENGLISH TEST SKILL-->
                <div class="skill-test-lists common-test-detail">
                    @foreach (var item in Model)
                    {
                        <div class="col-12 col-lg-12 col-sm-12">

                            <div> <h1 class="title22Bold mb-2"></h1></div>
                            <div class="row">
                                <div class="d9Box part-item">
                                    <a href="@Url.Action("DanhSachBai", "TracNghiem", new { id = item.LoaiBaiId })"><h2 class="title22Bold c065">@item.TenLoaiBai</h2></a>
                                    <div class="view-detail">
                                    </div>
                                    <div class="brLine margin-bottom-28"></div>
                                    <div class="progress-box">
                                        <div class="progress">
                                            <div class="progress-bar" style="width: 0%">
                                                <!--gray or green-->
                                            </div>
                                        </div>
                                    </div>
                                    <a href="@Url.Action("DanhSachBai", "TracNghiem", new { id = item.LoaiBaiId })" class="btn orange">Xem Chi Tiết</a>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <!--/ENGLISH TEST SKILL-->
    </div>
    <!--/LEFT CONTENT-->
    <!--LEFT CONTENT-->
    <div class="cot-phai" style="height: auto !important;">
        <nav id="sidebar" class="sidebar-right" style="height: auto !important;">
            <zone id="kunrhqdl"></zone>
            <script>arfAsync.push("kunrhqdl");</script>
    </div>
    </nav>
</div>
<!--/LEFT CONTENT-->